#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FragmentTutorial.Resource", IsApplication=true)]

namespace FragmentTutorial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public const int headlingsFragmentID = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int infoFragmentID = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int message_tvID = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int myButton = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int newsLinearLayout = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int newsStory_tvID = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int storyPlaceHolderID = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int InfoFragment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int StoryFragment = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int hello = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int text_from_static_fragment = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
